import { exec } from "child_process";
const names = [
  "stone-web3-fellow",
  "written-web3-positive",
  "actually-web3-win",
  "young-web3-fireplace",
  "far-web3-neck",
  "avoid-web3-plenty",
  "serious-web3-thank",
  "chose-web3-simple",
  "weight-web3-grabbed",
  "moonchrisir-web3-assets",
  "again-week",
  "fifth-sides",
  "clearly-this",
  "pattern-neck",
  "known-drew",
  "development-corn",
  "exercise-hit",
  "understanding-town",
  "swam-mainly",
  "seldom-announced",
  "shade-winter",
  // 'fully-sort',
  "sick-leaving",
  "fresh-lying",
  "shoe-zebra",
  "average-different",
  "possibly-hour",
  "outside-visitor",
  "tell-jump",
  "word-living",
  "basis-fat",
  "might-fog",
  "rich-chemical",
  "butter-love",
  "lot-vessels",
  "sides-movement",
  "donkey-pitch",
  "personal-information",
  "warm-health",
  "seat-needle",
  // 'attention-easily',
  "highway-doubt",
  "strong-answer",
  "automobile-might",
  "truth-rice",
  "alphabet-minute",
  "prove-solid",
  "section-instance",
  "observe-money",
  "structure-trip",
  "article-steep",
  "crack-past",
  "local-headed",
  "sell-substance",
  "construction-double",
  "swim-yet",
  "frog-wish",
  "heat-greater",
  "her-lucky",
  "sell-watch",
  "quite-young",
  "color-ability",
  "slip-carbon",
  "spite-door",
  "finest-blind-tin",
  "by-sum-desert",
  "completely-these-blood-troops",
  "no-goose-claws-girl",
  "making-month-test-name",
  "per-bank",
  "necessary-desk",
  "active-party-blew",
  "globe-poem-ancient",
  "nails-tight-aid",
  "slow-anyway-key-stomach",
  "wolf-whistle-problem-help",
  "congress-anywhere-watch-high",
  "certainly-check-shown",
  "property-previous-lack-interior",
  "shout-arrange-onto",
  "earlier-radio-sea-earlier",
  "trace-golden-owner",
  "especially-have-broke",
  "almost-shut",
  "basis-flag-cover",
  "aloud-produce-world",
  "receive-judge-common",
  "than-balloon-nation",
  "price-instance-directly",
  "evidence-simply-market",
  "bring-wheel-class-park",
  "difficulty-else",
  "form-society",
  "character-successful-water-arm",
  "became-experience-local-may",
  "ability-aloud",
  "ancient-cause-bright-foot",
  "bank-empty-shut-couple",
  "yes-fill-some-gravity",
  "voyage-light-breath",
  "author-wool-make",
  "passage-remain-minute-game",
  "afraid-pig-as",
  "cabin-return",
  "missing-require-then",
  "yesterday-agree-because",
  "power-eager-size",
  "younger-writing-on-physical",
  "dream-including-business",
  "street-wrote-sail",
  "paper-jump-mud",
  "anything-kitchen-pack-tears",
  "continued-quiet-previous-touch",
  "choice-extra-camera-problem",
  "three-drawn",
  "share-quite",
  "massage-square-studying-cross",
  "rising-valuable-lie",
  "balance-thousand-doctor",
  "organized-represent-vegetable-thick",
  "vapor-real-angle",
  "yard-bread",
  "city-hold-drive-selection",
  "matter-hunter-safety",
  "hospital-surprise-spread-depend",
  "location-captain-whatever-once",
  "leg-it-importance-can",
  "twice-harbor-deeply-realize",
  "upon-dollar-company-provide",
  "many-fed-wood",
  "escape-light",
  "fuel-split-small",
  "more-brief-prize",
  "whenever-surrounded-political",
  "manufacturing-detail-electric",
  "being-heard-nation-nature",
  "having-possible-grew",
  "term-average-military",
  "upward-hollow-touch",
  "cream-shown",
  "close-strip-sat",
  "rear-lie-visitor",
  "hair-parent-shirt-day",
  "anywhere-dream",
  "spring-molecular-news",
  "be-ocean-sell",
  "process-sometime-shop",
  "light-soon-his-lost",
  "sound-whom-fresh",
  "sides-compare-fighting-trunk",
  "explanation-mile-birthday",
  "practice-neighbor-lot",
  "gulf-list-section-stick",
  "prepare-pupil-money",
  "sort-zebra-how",
  "new-chair-shinning-national",
  "will-equally-equator",
  "rays-glass",
  "quickly-warm",
  "character-dirt-save",
  "government-information-occur-month",
  "carry-musical-must-mental",
  "tune-universe-muscle-pull",
  "column-word-orbit-which",
  "here-monkey",
  "stuck-answer",
  "dance-phrase-clock",
  "palace-needs-product-country",
  "old-gather-does",
  "jet-flew",
  "piano-disappear-keep-dance",
  "suggest-apart",
  "sheep-reason-sudden",
  "dot-paper-underline-bee",
  "shorter-bat-wagon-plus",
  "worth-mysterious-sort-ready",
  "seat-collect-hunter-public",
  "breakfast-thy-slip",
  "basic-separate-beauty-sea",
  "grabbed-stared-though-wing",
  "safety-follow-dug",
  "proud-bear-break",
  "mainly-should-song",
];



let projectName = ``
for (let index = 0; index < names.length; index++) {
    const element = names[index];
    projectName+=`${element} `
}
console.log(projectName);
// exec(`pnpm i ${projectName} -S`)
// function delay(ms = 1000*20) {
//   return new Promise((resolve) => setTimeout(resolve, ms));
// }
// const execute = async () => {
//   for (let index = 0; index < 100000; index++) {
//     try {
//       exec(`rm -rf node_modules`);
//       exec(`rm -rf pnpm-lock.yaml`);
//       exec(`pnpm store prune`);
//       exec(`pnpm install`, (error, stdout, stderr) => {
//         if (error) {
//           console.error(`Error: ${error.message}`);
//           return;
//         }
//         if (stderr) {
//           console.error(`Stderr: ${stderr}`);
//           return;
//         }
//         return;
//       });
//       await delay();
//     } catch (error) {}
//   }
// };
// execute();